on:
  schedule:
    - cron: "0 0 1 * *"  # Run every month
  # This way, we can make sure code doesn't break via external dependancies
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello world!"
